"use client";

import { useTheme } from "@/lib/theme-context";

// ─── Copy Keys ────────────────────────────────────────────────────────────────

export type CopyKey =
  // Auth
  | "appTitle"
  | "appEmblem"
  | "emptyEmblem"
  | "authSubtitle"
  | "authButton"
  | "authLocked"
  | "authWarning"
  | "bootLoading"
  // Dashboard header
  | "greetingPrefix"
  | "dateLabelCurrent"
  | "dateLabelPrefix"
  // Habit list
  | "activeHabits"
  | "habitCount"
  | "noHabits"
  | "noHabitsHint"
  // Add / Edit modal
  | "addHabitTitle"
  | "editHabitTitle"
  | "labelIcon"
  | "labelName"
  | "labelColor"
  | "labelSchedule"
  | "inputPlaceholder"
  | "subtasksLabel"
  | "addSubtaskButton"
  | "subtaskPlaceholder"
  | "savingText"
  | "saveButton"
  | "updateButton"
  // Schedule tabs
  | "scheduleDays"
  | "scheduleDates"
  | "scheduleFreqWeek"
  | "scheduleFreqMonth"
  | "targetLabel"
  // Detail modal
  | "detailSubtitle"
  | "executeButton"
  | "completedButton"
  | "streakLabel"
  | "successLabel"
  | "maxStreakLabel"
  | "timelineLabel"
  | "noteLabel"
  | "saveNoteButton"
  | "savingNoteText"
  | "deleteButton"
  | "deleteConfirm"
  | "notePlaceholder"
  | "dataPrefix"
  | "seqPrefix"
  // Daily progress
  | "allDone"
  | "allDoneHint"
  | "loadPrefix"
  | "pendingSuffix"
  // Daily plan
  | "planButtonCreate"
  | "planButtonEdit"
  | "planModalTitle"
  | "planModalHint"
  | "planEmptyState"
  | "planAutoTag"
  | "planSaveButton"
  | "addToPlanButton"
  // Progress page
  | "progressModule"
  | "progressTitle"
  | "scopeWeek"
  | "scopeMonth"
  | "streaksSection"
  | "overviewSection"
  | "yieldLabel"
  // Settings page
  | "settingsModule"
  | "settingsTitle"
  | "notifSection"
  | "notificationsLabel"
  | "notifLabel"
  | "notifTime"
  | "appearanceLabel"
  | "accountLabel"
  | "alertsLabel"
  | "timeLabel"
  | "logoutButton"
  | "signOutSection"
  | "signOutButton"
  | "themeSection"
  | "colorsLabel"
  | "colorSurface"
  | "colorScreen"
  | "colorPrimary"
  | "colorSuccess"
  | "colorText"
  | "colorDefault"
  | "colorCustom"
  | "colorsReset"
  | "wallpaperLabel"
  | "wallpaperUpload"
  | "wallpaperSourceTheme"
  | "wallpaperSourceCustom"
  | "wallpaperSourceNone"
  | "wallpaperFitCover"
  | "wallpaperFitContain"
  | "wallpaperFitTile"
  | "wallpaperZoom"
  | "wallpaperPosX"
  | "wallpaperPosY"
  | "wallpaperDim"
  | "wallpaperReset"
  | "wallpaperDragHint"
  | "toastWallpaperSaved"
  | "toastWallpaperFailed"
  | "userFallback"
  | "emailPrefix"
  | "versionText"
  | "copyrightText"
  // Nav
  | "navMain"
  | "navDiag"
  | "navCfg"
  // Toasts
  | "toastCreated"
  | "toastUpdated"
  | "toastArchived"
  | "toastPermDenied"
  | "toastAlertsOn"
  | "toastAlertsOff"
  | "toastNotifUnsupported"
  | "toastSaveFailed"
  | "streakUnitDay"
  | "streakUnitWeek"
  | "streakUnitMonth"
  | "skipButton"
  | "unskipButton"
  | "skippedLabel"
  | "archiveButton"
  | "archivedSection"
  | "archivedEmpty"
  | "restoreButton"
  | "pauseButton"
  | "resumeButton"
  | "pausedSection"
  | "pausedUntil"
  | "pausedIndefinitely"
  | "pauseUntilLabel"
  | "pauseConfirm"
  | "toastRestored"
  | "toastPaused"
  | "toastResumed"
  | "toastDeleted"
  | "historyLabel"
  | "historyHint"
  | "statusDone"
  | "statusMissed"
  | "statusOpen"
  | "statusInactive"
  | "typeLabel"
  | "typeCheck"
  | "typeMeasure"
  | "measureTargetLabel"
  | "unitLabel"
  | "unitPlaceholder"
  | "stepLabel"
  | "logValueLabel"
  | "timeOfDayLabel"
  | "todAnytime"
  | "todMorning"
  | "todAfternoon"
  | "todEvening"
  | "datesLabel"
  | "startDateLabel"
  | "endDateLabel"
  | "datesHint"
  | "challengeProgress"
  | "reminderLabel"
  | "reminderOnlyIfNotDone"
  | "arrangeButton"
  | "arrangeDone"
  | "cancelButton";

// ─── Hook ─────────────────────────────────────────────────────────────────────

// Each theme's dictionary lives in its definition (`lib/themes/<id>.ts`).

export function useCopy(): Record<CopyKey, string> {
  return useTheme().def.copy;
}
